### ISSUE TITLE
Access rights for ACOM, web conferences and advice drafting groups

### ISSUE THREAD

**Issue by colinpmillar** [ices-eg/WGTAFGOV#23]
### Summary

ADGs and web conferences may need to be able to look into the code and results from individual assessments.  A decision on who can access what needs to be decided. This should be considered by ACOM, as it may be overkill to allow all ACOM members full access to all assessment repositories.

### task list (draft - to be reviewed by TAFGOV)

- [ ] Work out the requirements - code, input data, results
- [ ] Make a proposal to ACOM
- [ ] Test implementation
- [ ] Implement in full

**Comment by jensr** [comment]
Does github support group permissions? E.g. can you establish groups for ACOM reviewers and then jsut add a single group to permissions? Not sure if github has a feature like that, and if it can be used to link across the ICES/ActiveDirectory type structure.

**Comment by colinpmillar** [comment]
Yes we can :) this is how we are starting to work now - we have groups (or teams in GH parlance) and the membership is based on the mebership in the ICES meetings system (RCT).  We have developing systems that monitor the ICES list of members and add or remove from the github teams (note the word developing, there are still teathing problems).  

I will need to understand how reviewers are recorded in RCT to understand how the case for reviewers will work, if they are members of the ADG then this will be easy.

**Comment by clordan** [comment]
My strong preference is to make all final assessment repositories available as read only to all ACOM members and alternates in advance of the ADG and WC.  Observers and non-ACOM participants should only be allowed to see the repos pertaining to their ADG.

**Comment by colinpmillar** [comment]
Discussions with Mark DC: agreed

**Comment by colinpmillar** [comment]
@colinpmillar to check with some ACOM members that they can access the assessment repositories.  This can be done during ACOM meeting 9/3/2021-10/3/2021

**Comment by colinpmillar** [comment]
User claims are now linked to the updated CRM (content resource managament) system in ICES, and we can identify the groups people are attached to (ACOM, ADGs etc). WHat needs to be done now is to open up the pages and repositories to ACOM and the apprporiuate ADG.

**Comment by colinpmillar** [comment]
users can check their claims in R using the icesConnect package, installed via:
```r
options(repos = c(
  icestoolsprod = 'https://ices-tools-prod.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages('icesConnect')
```

then run:
```r
icesConnect::decode_token()
```
to see a list of claims

**Comment by colinpmillar** [comment]
It is important to keep github access and ICES group membership in sync.  this would probably be done using a daily procedure that would add and remove members from the ices-taf and ices-eg group members.

We also need to communicate to ICES community that GitHub access to repos depends on linking your giothub username with your ICES account

**Comment by colinpmillar** [comment]
We have a system in place where we can manually update groups quickly and easily, the steps in the process are:
* check group membership within ICES systems
* For users who have connected thier GitHub account: invite them to the approprate groups (this includes ACOM)
* For users who have not connected thier GitHub, send an email informing them that if they wich access to GitHub resources to create a github account and link it with ICES (not active - ACOM chair wanted to ask ACOM members and EG chairs to encourage members to do this first, then we will activeate this step)
